---
regions:
  # san-francisco-bay_california:
  #   bbox:
  #     top: 38.719
  #     left: -123.640
  #     bottom: 36.791
  #     right: -121.025
  #   zoom_range: [0, 16]
  san-francisco-downtown:
    bbox:
      top: 37.7997
      left: -122.5109
      bottom: 37.7127
      right: -122.3636
    zoom_range: [0, 16]
outputs:
  - type: skadi
  - type: tiff
  - type: terrarium
  - type: normal
sources:
  - type: etopo1
    url: https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/georeferenced_tiff/ETOPO1_Bed_g_geotiff.zip
  - type: gmted
    url: http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/Global_tiles_GMTED
    ys: [-90, -70, -50, -30, -10, 10, 30, 50, 70]
    xs: [-180, -150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150]
    tries: 100
  - type: greatlakes
  - type: srtm
    url: http://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11
    mask-url: http://e4ftl01.cr.usgs.gov/MEASURES/SRTMSWBD.003/2000.02.11
    username: 'earthdata username'
    password: 'earthdata password'
    auth-url: https://urs.earthdata.nasa.gov
  - type: ned13
    ftp_server: rockyftp.cr.usgs.gov
    base_path: vdelivery/Datasets/Staged/NED/13/IMG
  - type: ned
    ftp_server: rockyftp.cr.usgs.gov
    base_path: vdelivery/Datasets/Staged/NED/19/IMG
  - type: ned_topobathy
    ftp_server: rockyftp.cr.usgs.gov
    base_path: vdelivery/Datasets/Staged/NED/19/IMG
  - type: dmr1
    uri: http://gis.arso.gov.si/lidar/dmr1
    fishnet_url: https://raw.githubusercontent.com/DavixDevelop/TerraLidar/master/mapzen_data/whitelist.yaml
logging:
  config: logging.example.config
